name: Update shas

on:
  push:
    branches: ["master"]

jobs:
  hash-updater:
    if: "github.event.head_commit.author.email != 'meowtomation@users.noreply.github.com' && github.event.head_commit.committer.email != 'meowtomation@users.noreply.github.com'"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - run: rm -rf index && find \( -name '*.srlm' -o -name '*.srls' -o -name '*.srll' \) -exec sh -c 'sha256sum "$1" >> index' _ '{}' \;
      - run: sha256sum index > index.sha256

      - name: Check for breaking changes
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        continue-on-error: true
        run: |
          git config --global user.email "meowtomation@users.noreply.github.com"
          git config --global user.name "meowtomation"
          git add .
          git commit -m "update hashes"
          git push
