name: API Baseline Updater

on:
  push:
    branches: [ "master" ]

jobs:
  baseline-updater:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - run: rm -rf index && find \( -name '*.srlm' -o -name '*.srls' \) -exec sh -c 'sha256sum "$1" >> index' _ '{}' \;
      - run: sha256sum index.shas > index.sha256

      - name: Check for breaking changes
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config --global user.email "meowtomation@users.noreply.github.com"
          git config --global user.name "meowtomation"
          git add .
          git commit -m "update api dump"
          git push
